/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import java.awt.image.BufferedImage;
import java.io.IOException;

public class App {
    public static void main(String[] args) {

        Outfit outfit = new Outfit(130, 3, 1, 3, 651, "ff0000", "00A9FF", "0055FF", "557F00", false);

        try {
            // Gera um png standBy
            BufferedImage mergedImage = ImageMerger.mergeImages(outfit);
            String outputPath = "app/src/main/resources/standby/merged_outfit.png";
            ImageMerger.saveImage(mergedImage, outputPath);

            // Cria o gif, obviamente
            GifBuilder.createGif(outfit, "app/src/main/resources/walkgif/output.gif");


            // System.out.println("Imagem mesclada salva em: " + outputPath);
        } catch (IOException e) {
            System.err.println("Erro ao mesclar as imagens: " + e.getMessage());
        }

    }
}
